"""Generando_tablas_completas

Revision ID: e17ac3bb295d
Revises: 
Create Date: 2026-04-16 09:27:32.337160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17ac3bb295d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('module_type', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_page_number'), 'pages', ['page_number'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages_iD', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('adjective', sa.String(length=30), nullable=False),
    sa.Column('person', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['pages_iD'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_country'), 'countries', ['country'], unique=False)
    op.create_table('idioms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=30), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('example', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pages_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idioms_phrase'), 'idioms', ['phrase'], unique=False)
    op.create_table('sayings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages_id', sa.Integer(), nullable=False),
    sa.Column('saying', sa.String(length=45), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('example', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pages_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sayings_saying'), 'sayings', ['saying'], unique=False)
    op.create_table('synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=30), nullable=False),
    sa.Column('synonym', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['pages_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_word'), 'synonyms', ['word'], unique=False)
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('base_form', sa.String(length=25), nullable=False),
    sa.Column('meaning', sa.String(length=25), nullable=False),
    sa.Column('present', sa.String(length=25), nullable=False),
    sa.Column('simple_past', sa.String(length=25), nullable=False),
    sa.Column('present_part', sa.String(length=25), nullable=False),
    sa.Column('past_part', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbs_base_form'), 'verbs', ['base_form'], unique=False)
    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=30), nullable=False),
    sa.Column('meaning', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['pages_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabularies')
    op.drop_index(op.f('ix_verbs_base_form'), table_name='verbs')
    op.drop_table('verbs')
    op.drop_index(op.f('ix_synonyms_word'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index(op.f('ix_sayings_saying'), table_name='sayings')
    op.drop_table('sayings')
    op.drop_index(op.f('ix_idioms_phrase'), table_name='idioms')
    op.drop_table('idioms')
    op.drop_index(op.f('ix_countries_country'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_pages_page_number'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
